Remove soft deprecated function bookmarkableShinyApp
insightsengineering/teal pull request #782
Opened 2022-11-22 15:35 UTC by chlebowa

Closes [this[(https://github.com/insightsengineering/teal/issues/756).

2022-11-22 17:45 UTC, mhallal1 commented on NEWS.md
> +* Removed deprecated function `root_modules`.
The NEWS entry has been added here but was not removed from line 41, please remove it.

2022-11-22 17:45 UTC, mhallal1 commented on NEWS.md
> +* Removed deprecated function `root_modules`.
and deprecated functions can be grouped in a single entry.

2022-11-23 23:01 UTC, donyunardi requested changes
I got this error message when trying to run a simple teal app:

```r
example("init", package="teal")
```

![image](https://user-images.githubusercontent.com/8597300/203660313-5a55abe4-c7df-4ff6-af72-4f9148d483b2.png)

Which was caused by this line:
https://github.com/insightsengineering/teal/blob/07d17d133c253dbcad46dc01198eb613aec11327/R/module_teal.R#L210

Maybe we can just remove this `if` statement?

2022-11-23 23:47 UTC, chlebowa commented
> (...) caused by this line:
> 
> https://github.com/insightsengineering/teal/blob/07d17d133c253dbcad46dc01198eb613aec11327/R/module_teal.R#L210
> 
> Maybe we can just remove this `if` statement?

I believe was part of the deprecated bookmarking mechanism. Removed altogether. Tests pass, example app works.

2022-11-24 00:22 UTC, donyunardi approved these changes
I saw this warning when adding teal.reporter card in exploratory app:
```r
[WARNING] Deprecated: --self-contained. use --embed-resources --standalone
```

I think this is pandoc related.

Otherwise, LGTM!

2022-11-24 00:22 UTC, merged